// Code generated by tygo. DO NOT EDIT.

//////////
// source: dreams_api.go


export function isDreamRequestBody(resp: unknown): resp is DreamRequestBody {
    const is = typeof (resp) == 'object' && resp != null &&
        'date' in resp && typeof (resp.date) == 'string' &&
        'description' in resp && (typeof (resp.description) == 'string' || resp.description == null)
    if (!is) {
        console.warn(resp, "is no DreamRequestBody")
    }
    return is
}
export interface DreamRequestBody {
    date: string /* RFC3339 */;
    description?: string;
}

export function isDreamResponse(resp: unknown): resp is DreamResponse {
    const is = typeof (resp) == 'object' && resp != null &&
        'id' in resp && typeof (resp.id) == 'number' &&
        'date' in resp && typeof (resp.date) == 'string' &&
        'description' in resp && typeof (resp.description) == 'string'
    if (!is) {
        console.warn(resp, "is no DreamResponse")
    }
    return is
}
export interface DreamResponse {
    id: number;
    date: string /* RFC3339 */;
    description: string;
}

export function isDreamsResponse(resp: unknown): resp is DreamsResponse {
    const is = typeof (resp) == 'object' && resp != null &&
        'dreams' in resp && Array.isArray(resp.dreams) && resp.dreams.every(v0 => isDreamResponse(v0))
    if (!is) {
        console.warn(resp, "is no DreamsResponse")
    }
    return is
}
export interface DreamsResponse {
    dreams: DreamResponse[];
}
